version: '3.8'
services:
  postgres-mirea:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student

    ports:
      - "5453:5432"
    volumes: 
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin-compose-mirea: 
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "student@kib.ru"
      PGADMIN_DEFAULT_PASSWORD: "kib!123!kib!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-mirea

